sudo: false
dist: trusty
language: node_js
node_js:
- 10
- 11
- 12
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run cover -- --runInBand
after_script:
- npm run report-coverage
env:
  global:
    secure: Jb9Q9+XnCh+n5uNJuqUmLmPG6mUUv7iTi5bNeK6TpLdrVKk+2mLdobV3iRUy/DEqNLwt2lxwzp1oq4YI/lZ0vlUam7HpFWpSf4PAI8ckGRqFdus7K45o+zxHLJ2zBQwXacsZB204qtO8RDdXaNb9PjRGNFdKm3ZuqZTv6PkO+hS05EFxmcW95HiSHpV/qPxKjEsDdCpoTNEA3MP0dNtSKygeht2nFQVr7WkOhkjDvUtU9EypkGbJeBCd0AckqXM0Qvmdi++csyz5VRQhhUwI/2BKSjbBVUZ6Q3m8sX2p4G/wFEbhXl5eKTzAYLuf+9kT9Jg+gKdT30PoChx2NPKHv0XS8BOrKQScs6KIwOVH2/CNCKqAxh3HkCMSONmqEQRqBK1V/gSCZ4zDX9PgrfyE23FLN/GM4YtBlkVCMLh8Y/hiapXUaDobxh/o2tfOoQkeoZWZeoeIydhwULTDSG2R3PKV7rkGYas0VQ+qtU+i8VG+PzjPT4DRf4xIKzNzJbFIq9oTNYBTasWi6+OKzNw0uH3ydmRzf+GxaTwOIdR3nRQMQN60dH+6qeJkrIvpfrGAB5gqTutXPfe0xf2rMrW6dyipnSgGlk1JOgA+cU4CPyHql1OA+ox/kIQ4I3PIJBu5YYE3amFmKLu3vnDHELSzM1CYeOs0sDasRyiDkKE79l0=
branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

jobs:
  include:
    - stage: deploy
      node_js: 12
      before_script:
        - chmod +x scripts/docs
      script: echo "Deploying ..."
      after_success:
        - scripts/docs
      branches:
        only:
        - master
        - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
      before_deploy:
      - echo 'Preparing to publish'
      - npm run build
      deploy:
        provider: npm
        email:
          secure: AUw8fn5gmJKKXzSvLs+vUZRz/htXtUAApRCy6SD7EZyQMHiFMfXCXdOIcSCyiOsxlvsh+Wv12qmfKySd3Yi3exeGbuZ/rQcK+i582iVBiBVRru2wcQ5iN9E21zgaRYk8c3lHWGDzorrJfr3dMbhmi4atmvrMg/u/jVLmz5h4Y8pHZeJ24WSl26NJo4WH2ibjOADfwKZmTH4jPMICKXpMvmUJ7K49LPE8MRHJRwSefadwtVcLuHHBqNOmDmUfNF9bEgTm0FnOtwEycsS6y1seB6pTOyidz9N5F5fB1eCyVuc/ev27Bvw6HL+i8anchtgGlGJyW/yL6yxycNfkGWaoJ243GhMbt4PTNwtiksolGvbgJ071yoRVqV/8m8tnTJWyShy16Y96hD2vFKV8lj4Fru3Ad8s0VU40ebslOa1IlzrmxxuUYOhX9Ir1ryHgnf7AEnVwie0p0IbJJY/SqPsa3kIyeoG9RePoruzS+v685GMRM+O7ZN34x4H2UogzWIql9IvpGAUdO5FDP9Ww8BkuLEv4myTZh7x4chqYLKQXoPIBzCzdbO8Hl4t7BYgFB2OLaTdcqPvjeANp7EtDzemCYFtNLuS34HKHQCwKcfr+Ar6/ZDlSKdWu0w7XC5jk0rYrDn97BKnbnNmn77d6ZWr6bzo439pCu91jW6DEyI6iAOM=
        api_key:
          secure: vnNNG+s14Yqnnj/ZjvMnAvsxd+QeLDlfo/iDA0EyHoFIBaSpApYoPzNd2FSZKyI/2kMYdKwUT40DF/qS+NBbhKY2M/HPUqomDny6Lw7XJKI7gTmtA2trlUR/fcHucOjW8PhMqQhB90J8J/RuWK2nS1Y3Mrhwtkbx0ShRl2mnWeysFOfrNywIi3bMDfUVWwQNcnC8c+w09F/S9tZKjjSSzcK9/raEwvZ2iSr2H6HRdlqf7JEl2H6F3k7ltx01FzIzdoTMAYsNENWDZfZUd8vfjmTfbtvVQC6n6uZd28PB1AGdsgy27aeBUe+C28UDlX6p3p6rRsPoLHXYx4hWlGmQvfIyl+vxlSiv8WcOJy2NnXnoJhMeYNmJVEQpBzWlI906z5UCn5+A3E+mPEKXg0jI/uQF5CFguMwwu2vl5N03ZNtD9tdFR0b53N+GCGkOF7jq7SeviR7b3/YmdHi9q5hFEmBXdYFzajxsaqUDYvHtVnjHSW3yT8pnxOvnG7JErg28bTdcYRHc//IVImjktFFsX85ukbGsgAwQAP9oVU0Wz7b0aQ0REnyW2aMroy1JGs8z/voM4aiNfvF6GwrBysWd4AYkalisjkq/LY1G3NDxU9gvPfRIIckgbQcgJ98eSHlG/2i7HqKlSH9Hf2LBAzkhwke3BTaI/hAuq3k0wDIVSY0=
        skip_cleanup: true
        on:
          tags: true