on:
  pull_request:
    branches: [master]
name: prerelease
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: npm version prerelease --preid=$GITHUB_HEAD_REF-`git rev-parse --short HEAD` --git-tag-version=false --commit-hooks=false
      - run: npm publish --tag prerelease-$GITHUB_HEAD_REF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Extract NPM package name
        run: echo "::set-output name=npm-name::`node -p -e "require('./package.json').name"`"
        id: npm-name
      - name: Extract npm package version
        run: echo "::set-output name=npm-version::`node -p -e "require('./package.json').version"`"
        id: npm-version
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Released prerelease version `${{ steps.npm-version.outputs.npm-version }}`.
            You may now run `npm install ${{ steps.npm-name.outputs.npm-name }}@${{ github.head_ref }}`
